name: levent_ozkan_personal_website
description: Levent ÖZKAN kişisel websitesi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  #state management
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1

  #routing
  auto_route: 4.2.1

  #localization
  easy_localization: ^3.0.1

  #ui
  gap: ^2.0.0
  flutter_svg: ^1.0.3
  video_player: ^2.4.7

  #firebase
  firebase_core: ^1.16.0
  firebase_storage: ^10.2.15
  cloud_firestore: ^3.1.14

  #core_utilities
  freezed_annotation: ^2.1.0
  json_annotation: 4.6.0

  google_fonts: ^3.0.1
  lottie: ^1.3.0
  animate_do: ^2.1.0
  flip_card: ^0.6.0
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.1.0
  carousel_slider: ^4.1.1
  simple_tooltip: ^1.0.0
  auto_size_text: ^3.0.0
  visibility_detector: ^0.3.0
  simple_animations: ^4.0.2
  supercharged: ^2.1.1
  draggable_scrollbar: ^0.1.0
  recase: ^4.0.0
  styled_text: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: 2.2.0
  auto_route_generator: 4.2.0
  freezed: 2.1.0+1
  json_serializable: 6.3.1

flutter:
  uses-material-design: true


  assets:
    - assets/svg/
    - assets/lottie/
    - assets/jpg/
    - assets/png/
    - assets/lang/
