name: levent_ozkan_personal_website
description: Levent ÖZKAN kişisel websitesi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  google_fonts: ^1.1.0
  get: ^3.24.0
  lottie: ^0.7.0+1
  animate_do: ^1.7.5
  flip_card: ^0.4.4
  flutter_svg: ^0.19.2+1
  flutter_vector_icons: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/svg/
    - assets/lottie/
    - assets/jpg/
    - assets/png/
